blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://github.com/@REPLACE_OWNER@/@REPLACE_REPO@/discussions
    about: Ask questions and discuss ideas with the community
  - name: Report Security Vulnerability
    url: https://github.com/@REPLACE_OWNER@/@REPLACE_REPO@/security/advisories/new
    about: Report security vulnerabilities privately
