name: finskew-deploy
run-name: deploy finskew

on:
  workflow_dispatch:
    inputs:
      runProvisioning:
        type: boolean
        default: false
        description: Run bicep template provisioning?

jobs:
  deploy:
    uses: ./.github/workflows/deploy-template.yml
    secrets: inherit
    with:
      runProvisioning: ${{ inputs.runProvisioning }}
